server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatisé…ç½®æ–‡ä»¶æ‰?åœ¨è·¯å¾?
  type-aliases-package: com.hengyangshiyuan.hrsystem.bean    # æ‰?æœ‰Entityåˆ«åç±»æ‰€åœ¨åŒ…
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapperæ˜ å°„æ–‡ä»¶
    
spring:
   application:
    name: hrsystem-manager
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # å½“å‰æ•°æ®æºæ“ä½œç±»å?
    driver-class-name: org.gjt.mm.mysql.Driver              # mysqlé©±åŠ¨åŒ?
    url: jdbc:mysql://localhost:3306/cloudDB01              # æ•°æ®åº“åç§?
    username: root
    password: 345177
    dbcp2:
      min-idle: 5                                           # æ•°æ®åº“è¿æ¥æ± çš„æœ€å°ç»´æŒè¿æ¥æ•°
      initial-size: 5                                       # åˆå§‹åŒ–è¿æ¥æ•°
      max-total: 5                                          # æœ?å¤§è¿æ¥æ•°
      max-wait-millis: 200                                  # ç­‰å¾…è¿æ¥è·å–çš„æœ€å¤§è¶…æ—¶æ—¶é—?